export const actionTypes = {
  FETCH_USERS: "FETCH_USERS",
  ADD_USER: "ADD_USER",
  LOAD_FRESH_BUS_DATA: "LOAD_FRESH_BUS_DATA",
  CONFIRM_BOOKING: "CONFIRM_BOOKING",
  FETCH_BUS_INFO: "FETCH_BUS_INFO",
  UPDATE_BOOKING: "UPDATE_BOOKING",
  CONFIRMATION_INFO: "CONFIRMATION_INFO",
  CLEAR_DATA: "CLEAR_DATA",
  LOADING: "LOADING",
  RESET_FORM: "RESET_FORM",
  DISPLAY_LIST: "DISPLAY_LIST",
};

export const USER = "USER";
